[package]
name = "kage"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0" }
tracing = { version = "0" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0" }
axum-extra = { version = "0", features = ["typed-header"] }
http = { version = "1" }
anyhow = { version = "1" }
redis = "0.24.0"
sea-orm = { version = "0", features = ["sqlx-mysql", "runtime-tokio", "macros"]}
oauth2-axum = "0.2.2"
dotenv = "0.15.0"
jsonwebtoken = "8.1.0"