[package]
name = "kage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version = "0" }
tracing = { version = "0" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0" }
axum-extra = { version = "0", features = ["typed-header"] }
http = { version = "1" }
redis = "0"
sea-orm = { version = "0", features = ["sqlx-mysql", "runtime-tokio", "macros"]}